version: 2

# https://circleci.com/blog/circleci-hacks-reuse-yaml-in-your-circleci-config-with-yaml/
defaults: &defaults
  docker:
    - image: cimg/go:1.17.13
  working_directory: /home/circleci/go/src/github.com/weaveworks/common

workflows:
  version: 2
  test-build-deploy:
    jobs:
    - lint
    - test

jobs:
  lint:
    <<: *defaults
    steps:
    - checkout
    - run:
        name: Lint
        command: |
          make lint

  test:
    <<: *defaults
    steps:
    - checkout
    - run:
        name: Test
        command: |
          make test
